PROJECT_PATH = r'C:\Users\bzakh\OneDrive\Documents\Python_Scripts\Networks_Science_2'

OUTPUT_PATH = PROJECT_PATH + r'\output'


JITTER_LOWEST_lOW = 0.01
JITTER_HIGHEST_LOW = 0.03
JITTER_LOWEST_HIGH = 0.05
JITTER_HIGHEST_HIGH = 0.08


CAPACITY_LOWEST = 1000
CAPACITY_HIGHEST = 10000

PROCESSING_SPEED_LOWEST = 100
PROCESSING_SPEED_HIGHEST = 1000

DISTORTION_PROBABILITY_LOWEST = 0
DISTORTION_PROBABILITY_HIGHEST = 100

DISTORTION_LEVEL_LOWEST = 0
DISTORTION_LEVEL_HIGHEST = 5

DROP_THRESHOLD = 0.8
BASIC_DROP_THRESHOLD = 0.7
