PROJECT_PATH = r'C:\Users\bzakh\OneDrive\Documents\Python_Scripts\Networks_Science_2'

OUTPUT_PATH = PROJECT_PATH + r'\output'


JITTER_LOWEST_lOW = 0.01
JITTER_HIGHEST_LOW = 0.03
JITTER_LOWEST_HIGH = 0.05
JITTER_HIGHEST_HIGH = 0.08

DEFAULT_JITTER_ACCURACY = 7

CAPACITY_LOWEST = 75 * 10**6 / 8
CAPACITY_HIGHEST = 150 * 10**6 / 8

PROCESSING_SPEED_LOWEST = 125 * 10**6 / 8
PROCESSING_SPEED_HIGHEST = 150 * 10**6 / 8

DISTORTION_PROBABILITY_LOWEST = 0
DISTORTION_PROBABILITY_HIGHEST = 100

DISTORTION_LEVEL_LOWEST = 0
DISTORTION_LEVEL_HIGHEST = 5

DEFAULT_FILLED_SPACE_FACTOR_LOW = 0.75
DEFAULT_FILLED_SPACE_FACTOR_HIGH = 1
DEFAULT_FILLED_SPACE_FACTOR_PLATEAU = 0.05

DROP_THRESHOLD = 0.8
BASIC_DROP_THRESHOLD = 0.99
