graph:
  path: C:\Users\bzakh\OneDrive\Documents\Python_Scripts\Networks_Science_2\Graph_Templates\wdigraph6.txt
   # ^ Указывается адрес на файл с матрицей смежности файла (txt, csv)
  type: standard
   # ^ Тип графа.
   # Возможные типы: standard, vmrk, mnrk, telnet,
   # vmrk_telnet, mnrk_telnet, tb_telnet, vmrk_tb_telnet, mnrk_tb_telnet
  options:
    inc_nodes: [1, 2, 6, 7, 8, 10, 11, 12, 15]
    dec_nodes: [3, 4, 5, 9, 13, 14, 18]